[package]
name = "aegistry-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { version = "5", features = ["chrono"] }
uuid = { workspace = true }
validator = { workspace = true }
